## Getting and knowing Data


In [1]:
import pandas as pd
import numpy as np

## Step1 

In [2]:
df = pd.read_csv("chipotle.tsv",sep = "\t")

In [3]:
df.head(5)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [4]:
df.shape

(4622, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


In [6]:
#print all column name
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [7]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [8]:
df.describe(include="all")

order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75 
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## loc vs iloc

In [9]:
df.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [10]:
df.loc[(df.item_name == "Nantucket Nectar") & (df.quantity == 2)]

order_id  quantity         item_name         choice_description  \
601        247         2  Nantucket Nectar  [Pineapple Orange Banana]   
2379       947         2  Nantucket Nectar             [Peach Orange]   

     item_price  
601      $6.78   
2379     $6.78

In [11]:
df.iloc[10]

order_id                                5
quantity                                1
item_name             Chips and Guacamole
choice_description                    NaN
item_price                         $4.45 
Name: 10, dtype: object

In [12]:
 type(df.iloc[10])

pandas.core.series.Series

In [13]:
df.iloc[[10]]

order_id  quantity            item_name choice_description item_price
10         5         1  Chips and Guacamole                NaN     $4.45

In [14]:
df.iloc[3:11]

order_id  quantity                              item_name  \
3          1         1  Chips and Tomatillo-Green Chili Salsa   
4          2         2                           Chicken Bowl   
5          3         1                           Chicken Bowl   
6          3         1                          Side of Chips   
7          4         1                          Steak Burrito   
8          4         1                       Steak Soft Tacos   
9          5         1                          Steak Burrito   
10         5         1                    Chips and Guacamole   

                                   choice_description item_price  
3                                                 NaN     $2.39   
4   [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5   [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                 NaN     $1.69   
7   [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8   [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9   [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25   
10                                                NaN     $4.45

In [15]:
df.iloc[3:6, :-1]

order_id  quantity                              item_name  \
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   

                                  choice_description  
3                                                NaN  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...  
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...

## Data Manipulation

In [16]:
 df.item_price.dtype

dtype('O')

## Apply

In [17]:
# df.item_price = df.item_price.apply(lambda x : float(x.replace('$','')))

In [18]:
df.head(5)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

## thêm một cột total_price

In [19]:
df["total_price"] = df["quantity"]*df["item_price"]

In [20]:
# df.total_price = df.quantity*df.item_price

In [21]:
df.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  \
0                                                NaN     $2.39    
1                                       [Clementine]     $3.39    
2                                            [Apple]     $3.39    
3                                                NaN     $2.39    
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98    

      total_price  
0          $2.39   
1          $3.39   
2          $3.39   
3          $2.39   
4  $16.98 $16.98

## How much the revenue for the period in the dataset ?

In [22]:
df["item_price"].sum()

'$2.39 $3.39 $3.39 $2.39 $16.98 $10.98 $1.69 $11.75 $9.25 $9.25 $4.45 $8.75 $8.75 $11.25 $4.45 $2.39 $8.49 $8.49 $2.18 $8.75 $4.45 $8.99 $3.39 $10.98 $3.39 $2.39 $8.49 $8.99 $1.09 $8.49 $2.39 $8.99 $1.69 $8.99 $1.09 $8.75 $8.75 $4.45 $2.95 $11.75 $2.15 $4.45 $11.25 $11.75 $8.75 $10.98 $8.99 $3.39 $8.99 $3.99 $8.99 $2.18 $10.98 $1.09 $8.99 $2.39 $9.25 $11.25 $11.75 $2.15 $4.45 $9.25 $11.25 $8.75 $8.99 $8.99 $3.39 $8.99 $10.98 $8.99 $1.69 $8.99 $3.99 $8.75 $4.45 $8.75 $8.75 $2.15 $8.75 $11.25 $2.15 $9.25 $8.75 $8.75 $9.25 $8.49 $8.99 $1.09 $9.25 $2.95 $11.75 $11.75 $9.25 $11.75 $4.45 $9.25 $4.45 $11.75 $8.75 $8.75 $4.45 $8.99 $8.99 $3.99 $8.49 $3.39 $8.99 $1.09 $9.25 $4.45 $8.75 $2.95 $4.45 $2.39 $8.49 $8.99 $8.49 $1.09 $8.99 $3.99 $8.75 $9.25 $4.45 $11.25 $4.45 $8.99 $1.09 $9.25 $2.95 $4.45 $11.75 $4.45 $8.49 $2.39 $10.98 $22.50 $11.75 $4.45 $11.25 $4.45 $11.25 $4.45 $11.25 $11.25 $11.75 $9.25 $4.45 $11.48 $17.98 $1.69 $17.50 $4.45 $8.49 $2.39 $17.50 $4.45 $4.45 $11.25 $11.75 $10.98 $8.

## Which is the most orderd items?

## Group by

In [111]:
c = df.groupby("item_name")["quantity"].sum()
c.sort_values(ascending = False).head(5)

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

# Unique Value

In [ ]:
df.item_name.value_counts().count()

In [ ]:
df.item_name.nunique()

# NUMPY

## random

In [53]:
import numpy as np

# zeros, ones , full , arange , linspace

In [54]:
np.zeros([2,4], dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
np.ones((3,5), dtype= float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
np.full((3,5),6.6)

array([[6.6, 6.6, 6.6, 6.6, 6.6],
       [6.6, 6.6, 6.6, 6.6, 6.6],
       [6.6, 6.6, 6.6, 6.6, 6.6]])

In [57]:
np.linspace(1,5,22)

array([1.        , 1.19047619, 1.38095238, 1.57142857, 1.76190476,
       1.95238095, 2.14285714, 2.33333333, 2.52380952, 2.71428571,
       2.9047619 , 3.0952381 , 3.28571429, 3.47619048, 3.66666667,
       3.85714286, 4.04761905, 4.23809524, 4.42857143, 4.61904762,
       4.80952381, 5.        ])

In [58]:
# Seed for reproduceibility
np.random.seed(0)

np.random.random((4,9))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492, 0.56804456, 0.92559664,
        0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936,
        0.78052918, 0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194, 0.26455561, 0.77423369,
        0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]])

In [59]:
np.random.rand(4,8)

array([[0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ,
        0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 , 0.31542835,
        0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952, 0.65310833,
        0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
        0.36872517, 0.82099323, 0.09710128]])

In [60]:
np.random.normal(0,1,(4,4))

array([[-0.02818223,  0.42833187,  0.06651722,  0.3024719 ],
       [-0.63432209, -0.36274117, -0.67246045, -0.35955316],
       [-0.81314628, -1.7262826 ,  0.17742614, -0.40178094],
       [-1.63019835,  0.46278226, -0.90729836,  0.0519454 ]])

In [61]:
np.random.randint(0,10,(4,5))

array([[1, 4, 6, 8, 2],
       [3, 0, 0, 6, 0],
       [6, 3, 3, 8, 8],
       [8, 2, 3, 2, 0]])

# Array indexing and Slicing

In [62]:
# One dimensional subarray

In [63]:
x1 = np.random.randint(20, size = 6)

In [64]:
x1

array([ 8,  8, 19,  8,  2,  3])

In [65]:
x1[3],x1[2]

(8, 19)

In [66]:
x1[3:]

array([8, 2, 3])

# Multi-dimentional array

In [67]:
x2 = np.random.randint(10,size=(3,4))

In [68]:
x2

array([[0, 4, 3, 6],
       [9, 8, 0, 8],
       [5, 9, 0, 9]])

In [69]:
x2[1][1]

8

In [70]:
x1[:4]

array([ 8,  8, 19,  8])

In [71]:
x1[:4]

array([ 8,  8, 19,  8])

In [72]:
x1[2:4]

array([19,  8])

In [73]:
x1[::2]

array([ 8, 19,  2])

## Reshaping of Array & Transpose

In [74]:
grid = np.arange(1,10)

In [75]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
grid.shape

(9,)

In [77]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
x= np.array([1,2,3])

In [79]:
x.shape

(3,)

In [80]:
x.reshape((1,3))

array([[1, 2, 3]])

In [81]:
import pandas as pd

In [82]:
df = pd.DataFrame([[1, 2], [4, 5], [7,None]],
     index=['cobra', 'viper', 'sidewinder'],
     columns=['max_speed', 'shield'])

In [23]:
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  \
0                                                   NaN     $2.39    
1                                          [Clementine]     $3.39    
2                                               [Apple]     $3.39    
3                                                   NaN     $2.39    
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98    
...                                                 ...        ...   
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75    
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75    
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25    
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75    
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75    

         total_price  
0             $2.39   
1             $3.39   
2             $3.39   
3             $2.39   
4     $16.98 $16.98   
...              ...  
4617         $11.75   
4618         $11.75   
4619         $11.25   
4620          $8.75   
4621          $8.75   

[4622 rows x 6 columns]

In [84]:
# df = df.loc[:,['max_speed']]

In [113]:
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  \
0                                                   NaN     $2.39    
1                                          [Clementine]     $3.39    
2                                               [Apple]     $3.39    
3                                                   NaN     $2.39    
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98    
...                                                 ...        ...   
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75    
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75    
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25    
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75    
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75    

         total_price  
0             $2.39   
1             $3.39   
2             $3.39   
3             $2.39   
4     $16.98 $16.98   
...              ...  
4617         $11.75   
4618         $11.75   
4619         $11.25   
4620          $8.75   
4621          $8.75   

[4622 rows x 6 columns]

In [86]:
df.dropna()

max_speed
cobra               1
viper               4
sidewinder          7